<?php
/**
 * Copyright (C) 2026 PatrikMol Solutions Kft. All rights reserved.
 *
 * Database adapter contract for the CronAdmin module.
 */

declare(strict_types=1);

namespace CronAdmin\Contracts;

/**
 * Minimal generic-SQL interface used by all CronAdmin classes.
 *
 * Hosts provide a concrete implementation (e.g. PdoAdapter or CallableAdapter)
 * that wraps their existing PDO connection. The module never touches PDO directly.
 */
interface DatabaseAdapterInterface
{
    /**
     * Fetches all rows matching the query.
     *
     * @param string  $sql
     * @param array   $params  Positional or named bind values.
     * @return array<int, array<string, mixed>>
     */
    public function fetchAll(string $sql, array $params = []): array;

    /**
     * Fetches a single row, or null if no row matches.
     *
     * @param string  $sql
     * @param array   $params
     * @return array<string, mixed>|null
     */
    public function fetchOne(string $sql, array $params = []): ?array;

    /**
     * Executes a write statement and returns the number of affected rows.
     *
     * @param string  $sql
     * @param array   $params
     * @return int  Affected row count.
     */
    public function execute(string $sql, array $params = []): int;

    /**
     * Returns the ID generated by the last INSERT statement.
     *
     * Behaviour mirrors PDO::lastInsertId() — returns '0' when no INSERT
     * has been performed yet, or on drivers that do not support it.
     *
     * @return string
     */
    public function lastInsertId(): string;

    /**
     * Wraps a callable in a database transaction.
     *
     * Begins a transaction, invokes $fn, commits on success, rolls back on
     * any Throwable, then re-throws. The module never calls beginTransaction,
     * commit, or rollBack itself — partial commits are impossible by design.
     *
     * @param callable $fn  Receives no arguments; return value is passed through.
     * @return mixed  Whatever $fn returns.
     * @throws \Throwable  Re-thrown after rollback if $fn throws.
     */
    public function withTransaction(callable $fn): mixed;
}
